[package]
name = "normalizer_glue"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
icu_normalizer = { version = "2.0.0", features = ["compiled_data", "utf16_iter", "latin1"] }
write16 = { version  = "1.0", features = ["smallvec"] }
smallvec = "1.9.0"
encoding_rs = "0.8"
